apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloudguard-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "kubernetes"
        static_configs:
          - targets: ["localhost:9090"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: cloudguard-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"