apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cloudguard
spec:
  selector:
    app: cloudguard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort